/* STATECRAFT — achievements. ACH(id, name, description, icon, condition) — conditions use the same syntax as events. */
const A = SC.ACH;
A('first_term','Sworn In','Complete your first quarter in office.','flag','turn>=1');
A('term_survivor','Full Term','Reach the end of your first term.','calendar','turn>=16');
A('re_elected','Re-elected','Win a second term.','ballot','term>=1');
A('hat_trick','Hat-trick','Win three elections in a row.','trophy','term>=3');
A('long_haul','Long Haul','Govern for 40 quarters.','hourglass','turn>=40');
A('landslide','Landslide','Poll above 60%.','crown','pop>.6');
A('economist','Economist','Growth above 4% with unemployment below 5%.','chartup','gdp_growth>.71 unemployment<.14');
A('full_employment','Full Employment','Unemployment below 3%.','briefcase','unemployment<.09');
A('no_poverty','War on Want','Halve poverty to below 10%.','tent','poverty<.25 turn>=8');
A('equality','A Fairer Society','Inequality below 30 with growth above 1%.','scales','inequality<.30 gdp_growth>.5');
A('safe_streets','Safe Streets','Crime below 15.','shield','crime<.15');
A('healthy','Healthy Nation','Public health above 80.','cross','health>.8');
A('scholar','Nation of Scholars','Education level above 80.','cap','education_level>.8');
A('green','Green Champion','Emissions below 25 and renewables above 60.','leaf','co2<.25 renewables>.6');
A('net_zero','Clean Slate','Pollution below 15.','sun','pollution<.15');
A('surplus','In the Black','Run a budget surplus.','bank','deficit_gdp<.49 turn>=4');
A('debt_free','Debt Free','Reduce debt below 20% of GDP after starting higher.','coin','debt_gdp<.08 turn>=8');
A('trust','Trusted','Trust in government above 75.','flag','trust_in_gov>.75');
A('clean','Clean Hands','Corruption below 10.','search','corruption<.10');
A('freedom','Bastion of Liberty','Civil rights above 85.','scales','civil_rights>.85');
A('respected','Respected','International standing above 80.','globe','international_standing>.8');
A('happy','Golden Age','Quality of life above 75.','sparkle','happiness>.75');
A('innovator','Innovation Nation','Innovation above 80.','bulb','innovation>.8');
A('homes','Homes for All','Housing affordability above 70.','house','housing_affordability>.7');
A('cohesion','United We Stand','Social cohesion above 80.','handshake','social_cohesion>.8');
A('peacemaker','Peacemaker','Sign three treaties.','handshake','treaty:trade treaty:peace');
A('victor','Victorious','Win a war.','tank','flag:won_war');
A('phoenix','Phoenix','Recover from a recession without losing office.','chartup','flag:recovered');
A('survivor','Survivor','Keep power with popularity below 30% for a quarter.','skull','pop<.3 turn>=6');
A('crisis_mgr','Crisis Manager','Govern through a pandemic.','virus','sit:pandemic');
A('reformer','Reformer','Move a policy from one extreme to the other.','sliders','flag:reformer');
A('populist','Man of the People','Poor, working class and middle class all above 60 mood.','people','mood:poor>.6 mood:working_class>.6 mood:middle_class>.6');
A('everybody','Everybody’s Friend','Every group above 55% mood.','heart','flag:everybody');
A('ubi','Basic Income','Introduce universal basic income.','coin','lvl:universal_basic_income>.4');
A('nuke','Nuclear Club','Acquire a nuclear deterrent.','atom','lvl:nuclear_arsenal>.5');
A('tax_free','Low Tax Nation','Total tax under 20% of GDP.','percent','tax_burden<.34 turn>=4');
A('big_state','Big State','Public spending above 50% of GDP.','building','spend_gdp>.72');
A('proportional','Fair Votes','Introduce proportional representation.','ballot','lvl:voting_system>.9');
A('coalition_pm','Coalition Builder','Serve in a coalition government.','handshake','coal');
A('emergency','State of Emergency','Invoke emergency powers.','alarm','emergency');
A('legend','Legend','Achieve a legacy score above 85.','star','flag:legend');
