/* Cabinet Edition interface: briefing desk and all expansion controls. */
(function(){
  const h=SC.h,UI=SC.UI;
  UI.GOOD='#356a4b';UI.BAD='#a34235';
  const pct=x=>Math.round(x*100)+'%';
  const costPct=x=>(x*100).toFixed(x<.01?2:1)+'%';
  const kv=(label,value)=>h('div',{class:'kv'},h('span',null,label),h('b',null,value));
  const note=text=>h('p',{class:'tip'},text);
  const tile=(label,value)=>h('div',{class:'stat-tile'},h('small',null,label),h('b',null,value));
  const action=(label,fn,style='')=>h('button',{class:'btn '+style,onclick:()=>{
    const r=fn();UI.toast(r?.msg||r?.why||'Order recorded');UI.renderTab(true);
  }},label);
  const select=(label,items,value)=>{const s=h('select',{'aria-label':label});for(const it of items){const [id,text]=Array.isArray(it)?it:[it,it];s.append(h('option',{value:id},text));}s.value=value;return s;};
  const field=(label,s)=>h('label',{class:'form-field'},h('span',null,label),s);
  const card=(title,...children)=>h('section',{class:'card'},h('h3',null,title),...children);
  const listJournal=(system,count=6)=>{const rows=UI.G.gov.journal.filter(j=>!system||j.system===system).slice(-count).reverse();return rows.length?h('div',{class:'journal'},rows.map(j=>h('div',{class:'journal-entry'},h('small',null,SC.quarterName(Math.max(0,j.turn-1),UI.G.startYear)),h('p',null,j.text)))):note('No reports yet. Actions resolve when you advance a quarter.');};
  const confirm = UI.confirm;
  UI.confirm = function(title,text,yes,no){ if(typeof yes === 'function') return confirm(title,text,'Confirm','Cancel').then(ok=>{if(ok)yes();}); return confirm(title,text,yes,no); };
  UI.SYSTEMS=[['leader','Head of government','people'],['party','Party & conference','parliament'],['donors','Donors & finances','coin'],['intel','Intelligence service','eye'],['health','Public health command','cross'],['referendum','Referendums','ballot'],['projects','National projects','hammer'],['press','Press office','news'],['regions','Regional governments','globe'],['assembly','World Assembly','handshake'],['war','War room','shield'],['scenario','Scenario objectives','flag']];
  UI.openSystem=function(id){UI.sub.system=id;UI.setTab('institutions');};
  UI.screens.institutions=function(){SC.ensureGov(UI.G);const id=UI.sub.system||'leader',s=UI.SYSTEMS.find(s=>s[0]===id)||UI.SYSTEMS[0];
    const picker=select('Government office',UI.SYSTEMS.map(s=>[s[0],s[1]]),id);picker.onchange=()=>{UI.sub.system=picker.value;UI.renderTab();};
    return h('div',{class:'office-screen'},h('div',{class:'screen-heading'},h('div',null,h('small',{class:'eyebrow'},'GOVERNMENT OFFICES'),h('h2',null,s[1])),picker),h('div',{class:'office-layout'},h('aside',{class:'office-directory'},UI.SYSTEMS.map(item=>h('button',{class:item[0]===id?'on':'',onclick:()=>UI.openSystem(item[0])},UI.icon(item[2],18),item[1]))),h('div',{class:'office-body'},UI.institutionViews[id]())));
  };
  UI.institutionViews={};
  UI.institutionViews.leader=function(){const G=UI.G,l=G.gov.leader,background=SC.EX.backgrounds.find(b=>b.id===l.background),perk=SC.EX.perks.find(p=>p.id===l.perk);
    return h('div',null,card('Personal dossier',h('div',{class:'leader-dossier'},UI.portrait(l,132),h('div',null,h('h2',null,l.name),note(G.parties[0].n+' · '+Math.floor(l.age)+' years old'),UI.tag(background.name),UI.tag(perk.name))),h('div',{class:'grid3'},tile('Health',pct(l.health)),tile('Stress',pct(l.stress)),tile('Experience',l.experience+' quarters')),note(background.desc),note(perk.desc)),card('Leadership decisions',note('Health and stress affect approval and capital income. Crises add stress. Recovery puts deputies in charge and reduces capital income for two quarters.'),h('div',{class:'action-row'},action('Rest & delegate · 4 PC',()=>SC.leaderAction(G,'rest')),action('Leadership training · 4 PC',()=>SC.leaderAction(G,'train')),h('button',{class:'btn danger',onclick:()=>UI.confirm('Arrange succession?','A successor takes office, keeping your background and perk. Approval drops temporarily.',()=>{const r=SC.leaderAction(G,'successor');UI.toast(r.msg||r.why);UI.renderTab();})},'Arrange succession · 10 PC'))),listJournal('leader'));
  };
  UI.institutionViews.party=function(){const G=UI.G;return h('div',null,note('Caucus loyalty changes legislative support and party unity. Conferences are held at most once a year and make a four-quarter policy pledge.'),G.gov.factions.map(f=>{const d=SC.EX.factions.find(d=>d.id===f.id);return card(d.name,kv('Share of the party',pct(d.share)),kv('Loyalty',pct(f.loyalty)),UI.bar(f.loyalty,UI.GOOD),note('Agenda: '+UI.N(d.policy).name+(d.dir>0?' expansion':' reduction')),f.pledge?note('Pledge: '+UI.polLabel(UI.N(f.pledge.policy),f.pledge.target)+' by '+SC.quarterName(f.pledge.by,G.startYear)):null,action('Endorse at conference · 6 PC',()=>SC.factionConference(G,d.id)));}),listJournal('party'));
  };
  UI.institutionViews.donors=function(){const G=UI.G,f=G.gov.finance;return h('div',null,h('div',{class:'grid3'},tile('Party treasury',f.cash.toFixed(1)+'m'),tile('Quarterly members’ income',f.income.toFixed(1)+'m'),tile('Scandal exposure',pct(f.scandal))),card('Grassroots funding',note('Party funds pay for election advertising, field campaigns and referendum campaigning. They do not come from the national budget.'),action('Hold fundraiser · 4 PC',()=>SC.fundraise(G))),SC.EX.lobbies.map(d=>{const offer=f.offers[d.id];return card(d.name,note('Seeks '+UI.N(d.policy).name+(d.dir>0?' expansion.':' reduction.')),offer?kv('Current contribution',offer.amount.toFixed(1)+' million'):note('Offers arrive on the next quarterly cycle.'),offer?action('Accept contribution · 2 PC',()=>SC.acceptDonation(G,d.id)):null);}),card('Commitments',f.deals.filter(d=>!d.done).map(d=>kv(UI.N(d.policy).name,UI.polLabel(UI.N(d.policy),d.target)+' · Q'+d.by)),!f.deals.some(d=>!d.done)?note('No open donor commitments.'):null),listJournal('donors'));
  };
  UI.institutionViews.intel=function(){const G=UI.G,v=G.gov.intel,target=select('Target nation',SC.D.nations.map(n=>[n.id,n.n]),G.war?.nation||SC.D.nations[0].id);
    return h('div',null,card('Service assessment',kv('Operational cover',pct(v.cover)),kv('Active missions',v.missions.length+' / 2'),field('Target delegation or rival',target),note('Two simultaneous operations are supported. Exposed missions can damage relations even when the operation succeeds. Authorization costs enter the next budget.'),v.missions.map(m=>kv(SC.EX.operations.find(d=>d.id===m.id).name,m.remaining+' quarters · '+pct(m.chance)+' estimated success'))),SC.EX.operations.map(d=>card(d.name,note(d.desc),kv('Authorization',UI.money(G.eco.gdp*d.cost)+' + '+d.pc+' PC'),kv('Duration',d.turns+' quarters'),action('Authorize operation',()=>SC.launchOperation(G,d.id,target.value)))),card('Intelligence reports',v.reports.slice().reverse().map(r=>kv(SC.EX.operations.find(d=>d.id===r.id).name,(r.success?'Success':'Failed')+(r.exposed?' · Exposed':' · Covert')))),listJournal('intel'));
  };
  UI.institutionViews.health=function(){const G=UI.G,p=G.gov.pandemic;
    const restrictions=select('Restrictions',[[0,'Open economy'],[1,'Targeted precautions'],[2,'Gathering restrictions'],[3,'Stay-at-home orders']],p.restrictions),testing=select('Testing',[[0,'Basic surveillance'],[1,'Community testing'],[2,'Mass testing & tracing']],p.testing),vaccines=select('Vaccination',[[0,'No national rollout'],[1,'Standard rollout'],[2,'Accelerated rollout']],p.vaccines);
    return h('div',null,card(p.active?'Active outbreak · quarter '+p.quarters:'National surveillance',h('div',{class:'grid3'},tile('Active infections',(p.i*100).toFixed(2)+'%'),tile('Vaccinated',pct(p.vaccinated)),tile('Cumulative deaths',p.deaths.toLocaleString())),kv('Susceptible population',pct(p.s)),kv('Recovered / immune',pct(p.r)),kv('Hospital resilience',Math.round(G.x.hospital_resilience*100)),p.history.length?UI.lineChart([{name:'Active infections',color:UI.BAD,vals:p.history.map(x=>x.i)},{name:'Vaccinated',color:UI.GOOD,vals:p.history.map(x=>x.v)}],{min:0,max:1,fmt:pct,xs:p.history.map(x=>x.turn)}):null),card('Public health orders',field('Restrictions',restrictions),field('Testing & tracing',testing),field('Vaccine campaign',vaccines),note('Restrictions suppress transmission but reduce growth and civil liberties. Testing reduces spread; vaccines reduce susceptibility. Hospital overload raises mortality. Vaccine-network policy increases rollout capacity.'),action('Adopt response · 2 PC',()=>SC.setPandemicResponse(G,{restrictions:+restrictions.value,testing:+testing.value,vaccines:+vaccines.value}))),listJournal('health'));
  };
  UI.policyPicker=function(label){return select(label,SC.D.policies.map(p=>[p.id,p.name]),'voting_system');};
  UI.institutionViews.referendum=function(){const G=UI.G,r=G.gov.referendum,policy=UI.policyPicker('Referendum policy'),level=h('input',{type:'number',min:0,max:UI.N(policy.value).steps,value:1,'aria-label':'Proposed policy level'});
    const levelLabel=h('small',null,'');const draw=()=>{const n=UI.N(policy.value);level.max=n.steps;level.value=Math.min(+level.value,n.steps);levelLabel.textContent='Current: '+UI.polLabel(n,G.pol[n.id].lvl)+' · Proposed: '+UI.polLabel(n,+level.value);};policy.onchange=draw;level.oninput=draw;draw();
    return h('div',null,r?card('Binding national vote',h('h2',null,UI.N(r.policy).name),kv('Proposed setting',UI.polLabel(UI.N(r.policy),r.target)),kv('Polling day',r.remaining+' quarters'),kv('Estimated Yes vote',pct(SC.referendumPoll(G,r))),note('This vote enacts the policy if Yes wins and prerequisites remain satisfied. The forecast is uncertain.'),action('Campaign for Yes · 3 PC + 3m',()=>SC.campaignReferendum(G))):card('Call a referendum',field('Policy',policy),field('Proposed level',level),levelLabel,note('Voting takes place after three quarters. Costs: 10 PC and 0.1% of GDP for administration. A rejected proposal hurts leader approval. Referendums remain subject to policy prerequisites.'),action('Call binding vote',()=>SC.callReferendum(G,policy.value,+level.value))),card('Results archive',G.gov.referendumHistory.slice().reverse().map(r=>kv(UI.N(r.policy).name,pct(r.share)+' Yes · '+(r.enacted?'Enacted':r.passed?'Prerequisites blocked':'Rejected')))),listJournal('referendum'));
  };
  UI.institutionViews.projects=function(){const G=UI.G;return h('div',null,note('Two programs can build simultaneously. Faster construction increases the annual appropriation. Paused work still has holding costs; completed projects have maintenance costs and permanent national benefits.'),SC.EX.projects.map(d=>{const p=G.gov.projects.find(p=>p.id===d.id&&p.status!=='cancelled');return card(d.name,note(d.desc),kv('Construction / maintenance',costPct(d.annual)+' / '+costPct(d.upkeep)+' of GDP per year'),kv('Base construction time',d.quarters+' quarters'),note('Requires '+UI.N(d.requires[0]).name+' at '+Math.round(d.requires[1]*100)),p?h('div',null,kv('Status',p.status),UI.bar(p.progress,UI.GOOD),kv('Progress / total spent',pct(p.progress)+' · '+UI.money(p.cost)),p.status!=='complete'?h('div',{class:'action-row'},action(p.status==='paused'?'Resume':'Pause',()=>SC.manageProject(G,d.id,p.status==='paused'?'resume':'pause')),action(p.pace>1?'Standard pace':'Accelerate · +50% spending',()=>SC.manageProject(G,d.id,p.pace>1?'standard':'accelerate')),h('button',{class:'btn danger',onclick:()=>UI.confirm('Cancel '+d.name+'?','Contract termination costs 0.1% of GDP and reduces public trust.',()=>{SC.manageProject(G,d.id,'cancel');UI.renderTab();})},'Cancel project')):note('Operational. Benefits are included in the simulation.')):action('Commission program · 8 PC',()=>SC.startProject(G,d.id)));}),listJournal('projects'));
  };
  UI.institutionViews.press=function(){const G=UI.G,p=G.gov.press,approach=select('Press approach',[['briefings','Factual briefings'],['spin','Aggressive spin'],['silence','Minimal engagement']],p.approach),focus=select('Press focus',['health','gdp_growth','crime','cost_of_living','national_security','housing_affordability'].map(id=>[id,UI.N(id).name]),p.focus);
    return h('div',null,card('Media monitoring',h('div',{class:'grid3'},tile('Credibility',pct(p.credibility)),tile('Scandal pressure',pct(p.pressure)),tile('Media tone',Math.round(G.x.media_tone*100))),note('Factual communication slowly builds confidence. Spin generates favorable coverage but erodes credibility, especially when independent reporting contradicts claims.')),card('Press strategy',field('Approach',approach),field('Briefing focus',focus),action('Set strategy · 2 PC',()=>SC.setPress(G,approach.value,focus.value)),h('div',{class:'action-row'},action('Leader briefing · 3 PC',()=>SC.pressAction(G,'brief')),action('Independent inquiry · 5 PC',()=>SC.pressAction(G,'inquiry')))),listJournal('press'));
  };
  UI.institutionViews.regions=function(){const G=UI.G;return h('div',null,card('The regional settlement',UI.map(G.regions,i=>G.gov.regions[i].services>.55?'#648568':'#b88961',{label:i=>G.regions[i].name.slice(0,9)}),note('Grants are proportional to population. Service delivery and unrest directly affect local election support. Regional administrations face elections every four years.')),G.gov.regions.map(r=>{const rg=G.regions[r.id],grant=select(rg.name+' grant',[[0,'Reduced grants'],[1,'Standard grants'],[2,'Priority investment']],r.grant),autonomy=select(rg.name+' autonomy',[[0,'Central direction'],[1,'Shared administration'],[2,'Devolved powers']],r.autonomy);return card(rg.name,h('div',{class:'row'},UI.portrait(r.governor,68),h('div',null,h('b',null,r.governor.name),note('Governor · competence '+pct(r.governor.comp)))),kv('Population share',pct(rg.pop)),kv('Services / unrest',pct(r.services)+' / '+pct(r.unrest)),kv('Government voting bonus',(r.voteBonus*100).toFixed(1)+' utility points'),field('Grant formula',grant),field('Autonomy',autonomy),h('div',{class:'action-row'},action('Set settlement · 2 PC',()=>SC.setRegion(G,r.id,+grant.value,+autonomy.value)),action('Replace governor · 5 PC',()=>SC.replaceGovernor(G,r.id))));}),listJournal('regions'));
  };
  UI.institutionViews.assembly=function(){const G=UI.G,a=G.gov.assembly;return h('div',null,card('Diplomatic standing',kv('Influence',Math.round(a.influence)+' / 100'),kv('Bloc membership',SC.EX.blocs.find(b=>b.id===a.bloc)?.name||'Independent'),note('Influence grows with international standing. Friendly delegations and targeted diplomacy make motions more likely to pass.')),card('International blocs',SC.EX.blocs.map(b=>h('div',{class:'bloc-row'},h('b',null,b.name),note(b.desc),note('Annual dues '+costPct(b.dues)+' of GDP · needs average relations '+b.min),action(a.bloc===b.id?'Withdraw · 6 PC':'Join · 6 PC',()=>SC.joinBloc(G,a.bloc===b.id?null:b.id))))),a.motion?card('Resolution under debate',h('h2',null,SC.EX.resolutions.find(d=>d.id===a.motion.id).name),kv('Vote scheduled',a.motion.remaining+' quarters'),SC.D.nations.map(n=>h('div',{class:'kv'},h('span',null,n.n+' · relations '+Math.round(G.world.nations[n.id].rel)),a.motion.lobbied.includes(n.id)?UI.tag('Approached'):action('Lobby · 2 PC + 5 influence',()=>SC.lobbyAssembly(G,n.id),'small')))):card('Table a resolution',SC.EX.resolutions.map(d=>h('div',{class:'bloc-row'},h('b',null,d.name),note('Implementation commitment '+costPct(d.cost)+' of GDP if adopted; effects last eight quarters.'),action('Propose · 5 PC + 20 influence',()=>SC.proposeMotion(G,d.id))))),card('Voting record',a.history.slice().reverse().map(m=>h('div',{class:'bloc-row'},kv(SC.EX.resolutions.find(d=>d.id===m.id).name,m.yes+'/'+m.total+' · '+(m.passed?'Adopted':'Rejected')),h('small',null,m.votes.map(v=>SC.natById(v.nation).n+': '+(v.yes?'Yes':'No')).join(' · '))))),listJournal('assembly'));
  };
  UI.institutionViews.war=function(){const G=UI.G;
    if(G.war){const w=SC.warDefaults(G.war),theatre=select('Concentrate forces',w.fronts.map((f,i)=>[i,f.name]),w.theatre),goal=select('War objective',[['defend','Defend the frontier'],['limited','Limited concessions'],['occupation','Occupation']],w.goal);
      return h('div',null,card('Strategic command',field('Concentration',theatre),field('Objective',goal),note('Concentrating forces accelerates progress in one theatre. Defence needs less momentum to conclude; occupation needs more and carries postwar costs and diplomatic damage.'),action('Issue strategic directive',()=>SC.setWarTheatre(G,+theatre.value,goal.value)),w.fronts.map(f=>h('div',{class:'front-report'},kv(f.name,Math.round(f.progress*100)+' control'),UI.sbar(f.progress,UI.GOOD)))),UI.polWorld(),listJournal('war'));
    }
    const nation=select('War target',SC.D.nations.map(n=>[n.id,n.n]),SC.D.nations[0].id),goal=select('War objective',[['defend','Frontier defence'],['limited','Limited concessions'],['occupation','Occupation']], 'limited');
    return h('div',null,card('Strategic readiness',note('No active conflict. Diplomatic tensions and military preparedness remain part of the simulation.'),UI.statRow('military_strength'),UI.statRow('national_security'),UI.statRow('supply_resilience')),G.warResult?card('Last conflict',kv('Outcome',G.warResult.outcome|| (G.warResult.won?'victory':'defeat')),kv('Casualties',G.warResult.casualties||0),kv('Operating cost',UI.money(G.warResult.cost||0))):null,card('Declare a conflict',field('Target nation',nation),field('Objective',goal),note('Requires relations of 10 or lower, no mutual defence treaty, and 18 PC. Declaring war reduces international standing. Costs increase with supply and mobilization.'),h('button',{class:'btn danger',onclick:()=>UI.confirm('Declare war?','Authorize military operations against '+SC.natById(nation.value).n+'?',()=>{const r=SC.declareWar(G,nation.value,goal.value);UI.toast(r.msg||r.why);UI.renderTab();})},'Declare war · 18 PC')),UI.polWorld());
  };
  UI.institutionViews.scenario=function(){const G=UI.G,s=G.gov.scenario,d=SC.EX.scenarios.find(d=>d.id===s.id);return h('div',null,card(d.name,note(d.desc),kv('Status',s.status),d.limit?kv('Time remaining',Math.max(0,d.limit-(G.turn-s.start))+' quarters'):note('Govern for as many terms as you can.'),SC.scenarioProgress(G).map(g=>h('div',{class:'kv'},h('span',null,g.label),UI.tag(g.ok?'Achieved':'Pending',g.ok?'good':'')))),note('Challenge completion is tracked separately from elections and government collapse. You may keep governing after a scenario deadline.'),listJournal('scenario'));
  };

  /* Briefing desk replaces the original graph as the landing screen; the graph remains available. */
  const graphScreen=UI.screens.board;
  UI.screens.board=function(){
    if(UI.sub.board==='graph')return h('div',{class:'network-screen'},h('button',{class:'btn network-back',onclick:()=>{UI.sub.board='briefing';UI.renderTab();}},'Return to briefing'),graphScreen());
    const G=UI.G,v=SC.ensureGov(G),b=SC.budget(G,true),s=SC.EX.scenarios.find(d=>d.id===v.scenario.id);
    const offices=UI.SYSTEMS.map(([id,name,icon])=>{
      const status={leader:pct(v.leader.health)+' health',party:pct(G.x.party_unity)+' unity',donors:v.finance.cash.toFixed(1)+'m in treasury',intel:v.intel.missions.length+' active missions',health:v.pandemic.active?'OUTBREAK ACTIVE':pct(v.pandemic.vaccinated)+' vaccinated',referendum:v.referendum?v.referendum.remaining+' quarters to vote':'No ballot scheduled',projects:v.projects.filter(p=>p.status==='building').length+' programs building',press:pct(v.press.credibility)+' credibility',regions:G.regions.length+' administrations',assembly:Math.round(v.assembly.influence)+' influence',war:G.war?'WAR WITH '+SC.natById(G.war.nation).n:'No active conflict',scenario:s.name};
      return h('button',{class:'office-card'+((id==='war'&&G.war)||(id==='health'&&v.pandemic.active)?' urgent':''),onclick:()=>UI.openSystem(id)},UI.icon(icon,24),h('div',null,h('b',null,name),h('small',null,status[id])),h('span',{class:'office-arrow'},'›'));
    });
    const due=v.factions.filter(f=>f.pledge).length+v.finance.deals.filter(d=>!d.done).length+v.campaign.pledges.filter(p=>!p.done).length;
    return h('div',{class:'briefing'},h('div',{class:'screen-heading'},h('div',null,h('small',{class:'eyebrow'},'CABINET BRIEFING / '+SC.quarterName(G.turn,G.startYear)),h('h1',null,G.C.name)),h('button',{class:'btn small',onclick:()=>{UI.sub.board='graph';UI.renderTab();}},UI.icon('sliders',18),'Policy network')),
      h('div',{class:'briefing-summary'},h('div',{class:'leader-summary'},UI.portrait(v.leader,84),h('div',null,h('small',{class:'eyebrow'},G.C.exec==='pm'?'PRIME MINISTER':'PRESIDENT'),h('h2',null,v.leader.name),note(G.parties[0].n),h('small',null,'Term '+(G.term+1)+' · '+Math.max(0,SC.electionIn(G))+' quarters to election'))),h('div',{class:'headline-stats'},tile('Voting intention',pct(G.poll.s[0])),tile('Projected annual deficit',(b.deficit/G.eco.gdp*100).toFixed(1)+'%'),tile('Political capital',G.o.sandbox?'Unlimited':Math.floor(G.pc)),tile('Open promises',due))),
      h('div',{class:'briefing-columns'},card('The national picture',UI.map(G.regions,i=>G.parties[G.regShare[i].indexOf(Math.max(...G.regShare[i]))].c,{label:i=>G.regions[i].name.slice(0,8),onTap:i=>UI.openSystem('regions')}),h('div',{class:'legend'},G.parties.map(p=>h('span',null,h('i',{style:{background:p.c}}),p.ab))),note('Map shows the leading party in each region. Select a region to manage its government.')),card('This quarter’s dispatches',v.journal.length?listJournal(null,5):h('div',{class:'journal'},h('div',{class:'journal-entry'},h('small',null,'THE MANDATE'),h('p',null,G.C.challenge)),h('div',{class:'journal-entry'},h('small',null,'TREASURY ADVICE'),h('p',null,'Set a medium-term fiscal framework and review the full budget before commissioning programs.')),h('div',{class:'journal-entry'},h('small',null,'CABINET SECRETARIAT'),h('p',null,'Government offices issue persistent quarterly orders. Open commitments and deadline reports will appear here.'))),G.news.length?h('div',{class:'newspaper'},h('small',{class:'eyebrow'},'IN THE PRESS'),h('p',null,G.news[0].text)):note('Advance a quarter to receive domestic and international reports.'))),
      h('div',{class:'screen-heading'},h('div',null,h('small',{class:'eyebrow'},'COMMAND & ADMINISTRATION'),h('h2',null,'Government offices')),h('small',null,'Choose an office to issue orders')),
      h('div',{class:'office-grid'},offices));
  };
  UI.newGameExtras=function(st){const background=select('Leader background',SC.EX.backgrounds.map(b=>[b.id,b.name]),st.background),perk=select('Leader perk',SC.EX.perks.map(p=>[p.id,p.name]),st.perk),scenario=select('Starting scenario',SC.EX.scenarios.map(s=>[s.id,s.name]),st.scenario);
    const descriptions=h('div'),draw=()=>descriptions.replaceChildren(note(SC.EX.backgrounds.find(b=>b.id===st.background).desc),note(SC.EX.perks.find(p=>p.id===st.perk).desc),note(SC.EX.scenarios.find(s=>s.id===st.scenario).desc));
    background.onchange=()=>{st.background=background.value;draw();};perk.onchange=()=>{st.perk=perk.value;draw();};scenario.onchange=()=>{st.scenario=scenario.value;draw();};draw();
    return card('4 · Your leader & mandate',field('Leader name',h('input',{'aria-label':'Leader name',placeholder:'Generate a name',value:st.leaderName,oninput:e=>st.leaderName=e.target.value.slice(0,50)})),field('Background',background),field('Perk',perk),field('Scenario',scenario),descriptions);
  };

  /* Budget planning supplements the existing tax and departmental breakdowns. */
  const economy=UI.screens.economy;
  UI.screens.economy=function(){const el=economy(),G=UI.G;
    if((UI.sub.eco||'budget')!=='budget')return el;
    const mode=select('Fiscal stance',[['balanced','Balanced framework'],['stimulus','Investment stimulus'],['consolidate','Credible consolidation']],G.gov.fiscal.mode),target=h('input',{type:'number',min:-5,max:15,step:.5,value:G.gov.fiscal.target*100,'aria-label':'Deficit target percent'});
    const forecast=SC.budgetForecast(G);
    el.prepend(card('Medium-term budget framework',field('Fiscal stance',mode),field('Annual deficit target (% GDP)',target),note('A target is a public commitment. It does not automatically change taxes or cut programs. Meeting it supports creditworthiness; missing it raises borrowing pressure. Stimulus adds 0.4% of GDP to annual investment spending.'),action('Adopt framework · 3 PC',()=>SC.setFiscalPlan(G,mode.value,+target.value/100)),UI.lineChart([{name:'Debt / GDP forecast',color:'#a77937',vals:[G.eco.debt/G.eco.gdp,...forecast.map(q=>q.debtRatio)]}],{xs:[G.turn,...forecast.map(q=>q.turn)],fmt:pct,h:140}),note('Projection holds current growth and planned fiscal ratios constant; it is an estimate, not a guarantee.')));
    return el;
  };
  const campaign=UI.polCampaign;
  UI.polCampaign=function(){const el=campaign(),G=UI.G,v=G.gov;
    el.prepend(card('Party war chest',kv('Available campaign funds',v.finance.cash.toFixed(1)+' million'),kv('Advertising last quarter',v.campaign.lastBudget.toFixed(1)+' million'),note('Advertising costs 4m per spending level each quarter. Raising the level also costs political capital. Insufficient cash reduces the campaign’s reach.')));
    if(SC.electionIn(G)<=4&&!G.o.sandbox){const policy=UI.policyPicker('Manifesto policy'),level=h('input',{type:'number',min:0,max:10,value:1,'aria-label':'Manifesto policy level'});policy.onchange=()=>{level.max=UI.N(policy.value).steps;level.value=Math.min(+level.value,+level.max);};policy.onchange();
      el.append(card('Field campaign & debate',h('div',{class:'action-row'},action('Ground campaign · 3 PC + 6m',()=>SC.campaignAction(G,'ground')),action('Televised debate · 3 PC + 3m',()=>SC.campaignAction(G,'debate'))),field('Manifesto policy',policy),field('Promised level',level),action('Make manifesto pledge · 3 PC',()=>SC.campaignAction(G,'pledge',policy.value,+level.value)),note('Promises must be fulfilled by six quarters after polling day. Keeping them improves trust; breaking them harms credibility.')));
    }
    el.append(card('Manifesto record',v.campaign.pledges.map(p=>kv(UI.N(p.policy).name,UI.polLabel(UI.N(p.policy),p.target)+' · '+(p.done?'Resolved':'Due Q'+p.by)))));
    return el;
  };
  /* Clear prerequisite feedback in both policy sheets and list controls. */
  const policyControl=UI.policyControl;
  UI.policyControl=function(n,onUpdate){const control=policyControl(n,onUpdate);const reqs=SC.EX.dependencies[n.id];if(reqs)control.prepend(h('div',{class:'policy-prerequisite'},'Prerequisites: '+reqs.map(([id,min])=>UI.N(id).name+' '+Math.round(min*100)+'%').join(' · ')));return control;};

  const showHelp = UI.showHelp; UI.showHelp = function(){ showHelp(); const sheet=UI.sheets[UI.sheets.length-1]; if(sheet) sheet.scroll.append(h('div',null,UI.section('Cabinet Edition field manual'),SC.EX.manual.map(([title,text])=>card(title,note(text))))); };

  UI.TABS=[['board','Briefing','home'],['policies','Policies','sliders'],['people','People','people'],['economy','Treasury','coin'],['politics','Politics','parliament'],['institutions','Offices','briefcase'],['more','Archive','menu']];
  UI.buildShell=function(){const root=UI.root();root.className='game-shell';
    const nav=h('nav',{class:'bottomnav'},h('div',{class:'nav-masthead'},h('small',null,'STATECRAFT'),h('b',null,'CABINET EDITION')),UI.TABS.map(t=>h('button',{'data-tab':t[0],onclick:()=>UI.setTab(t[0])},UI.icon(t[2],21),t[1])));
    root.replaceChildren(h('div',{class:'topbar',id:'topbar'}),nav,h('main',{class:'content',id:'content'}),h('div',{class:'office-footer'},h('span',null,'Every decision leaves a record.'),h('button',{class:'endturn',id:'endturn',onclick:()=>UI.endTurn()})));
  };
  const showMenu=UI.showMenu;UI.showMenu=function(){UI.root().className='';showMenu();};
  const renderTab=UI.renderTab;UI.renderTab=function(keepScroll){renderTab(keepScroll);const c=document.getElementById('content');if(c)c.classList.toggle('flush',UI.tab==='board'&&UI.sub.board==='graph');};
  const refresh=UI.refreshChrome;UI.refreshChrome=function(){refresh();const top=document.getElementById('topbar');if(top&&UI.G&&!top.querySelector('.office-brand'))top.prepend(h('div',{class:'office-brand'},UI.icon('parliament',22),h('b',null,'STATECRAFT'),h('small',null,'CABINET EDITION')));};
})();
