const assert = require('assert');
const { loadFiles, scriptsFromIndex } = require('./nodeload');
const { SC } = loadFiles(scriptsFromIndex(f => !f.includes('/ui/') && f !== 'js/main.js'));
SC.build();
const game = () => SC.newGame({ country: 'uk', party: 0, diff: 'normal', seed: 12345 });
const G = game(), id = SC.D.nations[0].id;
assert(SC.startWar(G, id).ok);
assert(!SC.setWarPlan(G, {strategy:'invalid', mobilization:0, supply:1}).ok);
assert(!SC.offerPeace(G).ok);
assert(SC.setWarPlan(G, {strategy:'offensive', mobilization:2, supply:2}).ok);
SC.warTurn(G);
assert(Number.isFinite(G.war.casualties) && G.war.casualties > 0);
assert(G.war.cost > 0 && G.war.weariness > 0);
const saved = SC.deserialize(SC.serialize(G));
assert.equal(saved.war.strategy, 'offensive');
assert.equal(saved.war.casualties, G.war.casualties);
const old = game(); old.war = {nation:id,turns:1,dur:4,momentum:0}; SC.warTurn(old);
assert(Number.isFinite(old.war.readiness));
G.war.turns = 8; assert(SC.offerPeace(G).ok); assert.equal(G.warResult.outcome,'ceasefire'); assert(!G.sitForce.at_war);
const win = game(); SC.startWar(win,id); win.war.turns=3; win.war.momentum=1.5; SC.warTurn(win); assert(win.warResult.won);
const loss = game(); SC.startWar(loss,id); SC.endWar(loss,'defeat'); assert.equal(loss.warResult.outcome,'defeat');
console.log('War tests passed: orders, costs, casualties, save/load, legacy saves, peace, victory and defeat.');
